### ISSUE TITLE
Description on hub.docker.com is incomplete.

### ISSUE THREAD

**Issue by sebastian-philipp** [fonk/docker-dudle#1]
Hi,

on hub.docker.com, please add an example command line that binds port 80 of the container to the host machine and add an example link to dudle's home page (e.ge. `http://localhost:8080/dudle/`, as `/` will only point to Apache's default page.

Thanks.

**Comment by fonk** [comment]
Thanks for the hint :-) Fixed in commit b979a4c80364e6ea1bb0e9faeb75e3c17d6fa4c7
